config/routes.rb
Rails.application.routes.draw do
    resources :products
    resources :users
    resource :session
    
    namespace :admin do
      resources :products
      
      root to: 'products#index'
    end
    
    root to: 'products#index'
end

app/models/product.rb
require 'httparty'
require 'json'

class Product < ActiveRecord::Base
  
  def post_to_eventbrite
   # @url_new_string = 'https://www.eventbriteapi.com/v3/categories/?token='+ENV['EVENTBRITE_KEY']
   # HTTParty.get(@url_new_string.to_s)
   @url_new_string = 'https://www.eventbriteapi.com/v3/events/?token='+ENV['EVENTBRITE_KEY']
   @result = HTTParty.post(@url_new_string.to_s,
     :body => { "events": [
        {
            "name": {
                "text": "Test Event 111",
                "html": "Test Event 111"
            },
            "start": {
              "timezone": "America/Los_Angeles"
            },
            "end": {
              "timezone": "America/Los_Angeles"
            },
            "currency": "USD"
        }
    ]}.to_json)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :role, inclusion: %w(admin user)
  
  def admin?
    self.role == 'admin'
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :ensure_admin_user!
  
  def ensure_admin_user!
    unless current_user&.admin?
      redirect_to root_path, danger: "Restricted"
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  
    def index
      @products = Product.order("updated_at DESC")
    end
    
    def new
      @product = Product.new
    end
    
    def show
      @product = Product.where(id: params[:id]).first
    end
    
    def edit
      @product = Product.where(id: params[:id]).first
    end
    
    def update
      @product = Product.where(id: params[:id]).first
      
      if @product.update_attributes(product_params)
        redirect_to admin_products_path
      else
        render :update
      end
    end
    
    def destroy
      @product = Product.where(id: params[:id]).first
      
      if @product.destroy
        redirect_to admin_products_path
      else
        render :update
      end
    end
    
    private
    
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  add_flash_types :danger, :info, :warning, :success
  
  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end
  
  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order("updated_at DESC")
  end
  
  def show
    @product = Product.where(id: params[:id]).first
  end
  
  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.where(email: params[:email]).first

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, success: "You have signed in"
    else
      redirect_to new_session_path, danger: "Invalid email or password"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to root_path
    else
      #error
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_user_auth_nav
   if current_user 
     render 'signed_in'
   else 
     render 'signed_out'
   end 
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/products/_form.html.erb
<%= form_for @product do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :currency %>
    <%= f.text_field :currency, value: "USD", class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time, value: "2018-02-07T13:00:00Z", class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :start_zone %>
    <%= f.text_field :start_zone, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time, value: "2018-02-07T14:00:00Z", class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :end_zone %>
    <%= f.text_field :end_zone, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit "Save",  class: 'btn btn-block btn-success' %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div class="actions col-md-8 col-md-offset-2">
  <div class="product">
    <h2>Name: <%= link_to item.name, admin_product_path(item) %></h2>
    <ul>
      <li>description: <%= item.description %></li>
      <li>price: <%= item.price %></li>  
      <li>currency: <%= item.currency %></li>
      <li>start time: <%= item.start_time %></li>
      <li>start time zone: <%= item.start_zone %></li>
      <li>end time:<%= item.end_time %></li>
      <li>end time zone: <%= item.end_zone %></li>
    </ul>
    
    <div class="col-md-3">
      <%= link_to "Edit", edit_admin_product_path(item), class: 'btn btn-primary' %>
    </div>
    <div class="col-md-3">
      <%= link_to "Delete", admin_product_path(item), method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>    
</div>

app/views/admin/products/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render partial: "form", locals: {product: @product} %>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-md-8">
    <% @products.each do |item| %>
      <%= render partial: "product", locals: {item: item} %>
    <% end %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render partial: "form", locals: {product: @product} %>
</div>

app/views/admin/products/show.html.erb
<ul>
  <li>description: <%= @product.description %></li>
  <li>price: <%= @product.price %></li>  
  <li>currency: <%= @product.currency %></li>
  <li>start time: <%= @product.start_time %></li>
  <li>start time zone: <%= @product.start_zone %></li>
  <li>end time:<%= @product.end_time %></li>
  <li>end time zone: <%= @product.end_zone %></li>
</ul>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="navbar-header">
          <%= link_to 'Event Machine', root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <%= render_user_auth_nav %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/application/_signed_in.html.erb
<li>
  <%= link_to current_user.email, admin_root_path %>
</li>
<li>
  <%= link_to "Add a Product", new_admin_product_path %>
</li>
<li>
  <%= link_to 'Sign out', session_path, method: :delete %>
</li>

app/views/application/_signed_out.html.erb
<li>
  <%= link_to 'Sign in', new_session_path %>  
</li>
<li>
  <%= link_to 'Sign up', new_user_path %>  
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventMachine</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'navbar' %>
    <div id='main' class='container'>
      <% flash.each do |name, value| %>
        <div class="alert alert-<%= name %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<div class="actions col-md-8 col-md-offset-2">
  <div class="product">
      <h2>Name: <%= link_to item.name, product_path(item) %></h2>
    <ul>
      <ul>
        <li>description: <%= item.description %></li>
        <li>price: <%= item.price %></li>  
        <li>currency: <%= item.currency %></li>
        <li>start time: <%= item.start_time %></li>
        <li>start time zone: <%= item.start_zone %></li>
        <li>end time:<%= item.end_time %></li>
        <li>end time zone: <%= item.end_zone %></li>
      </ul>
    </ul>
  </div>    
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="actions col-md-8 col-md-offset-2">
    <%= link_to "Add a Product", new_product_path %>
  </div>
  <br>
  <div class="row">
    <% @products.each do |item| %>
      <%= render partial: "product", locals: {item: item} %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<ul>
  <li>description: <%= @product.description %></li>
  <li>price: <%= @product.price %></li>  
  <li>currency: <%= @product.currency %></li>
  <li>start time: <%= @product.start_time %></li>
  <li>start time zone: <%= @product.start_zone %></li>
  <li>end time:<%= @product.end_time %></li>
  <li>end time zone: <%= @product.end_zone %></li>
</ul>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Register</h2>    
    
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h3>
            <%= pluralize(@user.errors.count, 'error') %>
            stopped this form from saving
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>      
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>        
      </div>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control' %>   
      </div>
      <div class='form-group'>
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class: 'form-control' %>   
      </div>
      <div class="actions">
        <%= f.submit "Finish", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>